### ISSUE TITLE
can't locate /docker/symfony.sh > Block migration

### ISSUE THREAD

**Issue by Juju075** [Juju075/symfony-devops#6]
docker-compose

```
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - database
```
dockerfile:

RUN cd /var/www/  (container) for the dependencies.

but last layer
`ENTRYPOINT ["bash", "/docker/symfony.sh"]`
